// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKTKVxYZIDpxyF8_wtuKTKxKKY5a3GrRA',
    appId: '1:474571153170:web:3f50dbf0a0d3077e4a5dcb',
    messagingSenderId: '474571153170',
    projectId: 'aya-test-99b66',
    authDomain: 'aya-test-99b66.firebaseapp.com',
    storageBucket: 'aya-test-99b66.appspot.com',
    measurementId: 'G-B39J6WYMT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8P_Ti-a63vy3k2C9ZBtOIx2WtxF0RLQY',
    appId: '1:474571153170:android:b90e66de49c28dcf4a5dcb',
    messagingSenderId: '474571153170',
    projectId: 'aya-test-99b66',
    storageBucket: 'aya-test-99b66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBywmTVwcTs1XOp6dJdfCunuJVsAKjiRzU',
    appId: '1:474571153170:ios:5312c8a14281c7784a5dcb',
    messagingSenderId: '474571153170',
    projectId: 'aya-test-99b66',
    storageBucket: 'aya-test-99b66.appspot.com',
    iosClientId: '474571153170-9ercerk0plhugepmq2aoqm0kns3p4lqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBywmTVwcTs1XOp6dJdfCunuJVsAKjiRzU',
    appId: '1:474571153170:ios:df0e38801765fce74a5dcb',
    messagingSenderId: '474571153170',
    projectId: 'aya-test-99b66',
    storageBucket: 'aya-test-99b66.appspot.com',
    iosClientId: '474571153170-c5noee41c73ve3p787pe5kd5ou9a58ne.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp.RunnerTests',
  );
}
